// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfxilgxlsxmruvdpkblt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmeGlsZ3hsc3htcnV2ZHBrYmx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4NTA2NjYsImV4cCI6MjA1NjQyNjY2Nn0.AooulzqwAI1_LWOAJZ2pjT49eaTe_EjZSVGRmeaFfF4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);